//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_zRMrsQuwEe-G3LyoK6aokAActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Plan_for_next_iteration_7A1635D4_7a1635d4_Activity.jpeg"
contentPage.processPage.imageFiles["_3L_40Q7bEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Conceive_New_Project_CDEDCE7F_cdedce7f_Activity.jpeg"
contentPage.processPage.imageFiles["_7pydUQ7cEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Evaluate_Project_Scope_and_Risk_86DA71B1_86da71b1_Activity.jpeg"
contentPage.processPage.imageFiles["_JSw0cQ7dEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Develop_Software_Development_Plan_9969BBE2_9969bbe2_Activity.jpeg"
contentPage.processPage.imageFiles["_mlK-kQ7dEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Manage_Iteration_24614C99_24614c99_Activity.jpeg"
contentPage.processPage.imageFiles["_yoZf4Q7dEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Close-out_Project_BA84AB71_ba84ab71_Activity.jpeg"
contentPage.processPage.imageFiles["_KO2MwQ7eEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Close-out_Phase_807B006C_807b006c_Activity.jpeg"
contentPage.processPage.imageFiles["_W8lDoQ7eEe-M7Mlv4-jcCwActivity"]="./../../ProjectManagement/capabilitypatterns/resources/Monitor_and_Control_Project_C81FC20E_c81fc20e_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_eOmzEQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Close-out_Phase_CEFC93B1_feb509c5_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_YlqNkQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Manage_Iteration_60F1C0C4_90aa36d8_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_UnxbsQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Evaluate_Project_Scope_and_Risk_EB5851EF_1b10c803_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_dSNcQQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Close-out_Project_2AC98AB2_5a8200c6_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_hv-BAQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Develop_Software_Development_Plan_55D8A7C1_85911dd5_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_fVMAoQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Plan_for_next_iteration_2E758E14_5e2e0428_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_TZGpIQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Conceive_New_Project_1247A085_42001699_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_WHStsQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Develop_Software_Development_Plan_154639DE_44feaff2_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_i3jUIQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Monitor_and_Control_Project_2A1A888B_59d2fe9f_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_Xf77oQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Plan_for_next_iteration_AC2473BE_dbdce9d2_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Proceso_2C7F27C0_2c7f27c0_Activity.jpeg"
contentPage.processPage.imageFiles["_7oodkQ8aEe-Sh6UbRcOx-w,_Z1tgMQ8bEe-Sh6UbRcOx-wActivity"]="./../../ProjectManagement/deliveryprocesses/resources/Evaluate_Project_Scope_and_Risk_C3A775FC_f35fec10_Activity.jpeg"
contentPage.processPage.elementUrls["_qg83oQ7dEe-M7Mlv4-jcCw"] = ["Iteration_Assessment","ProjectManagement/workproducts/iteration_assessment_6D021373.html"];
contentPage.processPage.elementUrls["_rIq-8A7dEe-M7Mlv4-jcCw"] = ["Acquire_Staff","ProjectManagement/tasks/acquire_staff_61E62DDF.html"];
contentPage.processPage.elementUrls["_a-zi8Q7eEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_sGUS8Q7dEe-M7Mlv4-jcCw"] = ["Work_Order","ProjectManagement/workproducts/work_order_CBF0790A.html"];
contentPage.processPage.elementUrls["_p3xXwA7dEe-M7Mlv4-jcCw"] = ["Test_Plan","ProjectManagement/workproducts/test_plan_9B12202C.html"];
contentPage.processPage.elementUrls["_4dgSFw7dEe-M7Mlv4-jcCw"] = ["Iteration_Assessment","ProjectManagement/workproducts/iteration_assessment_6D021373.html"];
contentPage.processPage.elementUrls["_a-zi8A7eEe-M7Mlv4-jcCw"] = ["Monitor_Project_Status","ProjectManagement/tasks/monitor_project_status_B702C02.html"];
contentPage.processPage.elementUrls["__SPxwA7cEe-M7Mlv4-jcCw"] = ["Identify and assess Risks","ProjectManagement/tasks/identify_and_assess_risks_2485C8B9.html"];
contentPage.processPage.elementUrls["_suma8w7dEe-M7Mlv4-jcCw"] = ["Vision","ProjectManagement/workproducts/vision_7A95AF30.html"];
contentPage.processPage.elementUrls["_5YLKkQ7dEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_O6lYlw7dEe-M7Mlv4-jcCw"] = ["Vision","ProjectManagement/workproducts/vision_7A95AF30.html"];
contentPage.processPage.elementUrls["_MHESpw7eEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_a-zi9Q7eEe-M7Mlv4-jcCw"] = ["Risk_Management_Plan","ProjectManagement/workproducts/risk_management_plan_EF36C2DA.html"];
contentPage.processPage.elementUrls["_O6lYkw7dEe-M7Mlv4-jcCw"] = ["Risk List","ProjectManagement/workproducts/risk_list_9879812E.html"];
contentPage.processPage.elementUrls["_suma-Q7dEe-M7Mlv4-jcCw"] = ["Status_Assessment","ProjectManagement/workproducts/status_assessment_803C2A35.html"];
contentPage.processPage.elementUrls["_R9g-EQ7dEe-M7Mlv4-jcCw"] = ["Product_Acceptance_Plan","ProjectManagement/workproducts/product_acceptance_plan_715D9C9A.html"];
contentPage.processPage.elementUrls["_Z1tgMQ8bEe-Sh6UbRcOx-w"] = ["Evaluate_Project_Scope_and_Risk","ProjectManagement/deliveryprocesses/Evaluate_Project_Scope_and_Risk_C3A775FC.html"];
contentPage.processPage.elementUrls["_4dgSFQ7dEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_TZGpIQ8bEe-Sh6UbRcOx-w"] = ["Conceive_New_Project","ProjectManagement/deliveryprocesses/Conceive_New_Project_1247A085.html"];
contentPage.processPage.elementUrls["_fVMAoQ8bEe-Sh6UbRcOx-w"] = ["Plan_for_next_iteration","ProjectManagement/deliveryprocesses/Plan_for_next_iteration_2E758E14.html"];
contentPage.processPage.elementUrls["_suma-w7dEe-M7Mlv4-jcCw"] = ["Test_Evaluation_Summary","ProjectManagement/workproducts/test_evaluation_summary_161A95D8.html"];
contentPage.processPage.elementUrls["_U2IxAA7dEe-M7Mlv4-jcCw"] = ["Develop_Quality_Assurance_Plan","ProjectManagement/tasks/develop_quality_assurance_plan_33722C62.html"];
contentPage.processPage.elementUrls["_p3oN0A7dEe-M7Mlv4-jcCw"] = ["Iteration_Evaluation_Criteria_Review","ProjectManagement/tasks/iteration_evaluation_criteria_review_1560CAE6.html"];
contentPage.processPage.elementUrls["_ESkGdw7cEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["_eOmzEQ8bEe-Sh6UbRcOx-w"] = ["Close-out_Phase","ProjectManagement/deliveryprocesses/Close-out_Phase_CEFC93B1.html"];
contentPage.processPage.elementUrls["_i3jUIQ8bEe-Sh6UbRcOx-w"] = ["Monitor_and_Control_Project","ProjectManagement/deliveryprocesses/Monitor_and_Control_Project_2A1A888B.html"];
contentPage.processPage.elementUrls["_5YLKkA7dEe-M7Mlv4-jcCw"] = ["Prepare_for_Project_Close_out","ProjectManagement/tasks/prepare_for_project_close_out_9A7AC55D.html"];
contentPage.processPage.elementUrls["_4dgSEw7dEe-M7Mlv4-jcCw"] = ["Status_Assessment","ProjectManagement/workproducts/status_assessment_803C2A35.html"];
contentPage.processPage.elementUrls["_a-zi8w7eEe-M7Mlv4-jcCw"] = ["Measurement_Plan","ProjectManagement/workproducts/measurement_plan_DBFCF019.html"];
contentPage.processPage.elementUrls["_ESkGcA7cEe-M7Mlv4-jcCw"] = ["Project Approval Review","ProjectManagement/tasks/project_approval_review_75D56B96.html"];
contentPage.processPage.elementUrls["_AsjMkQ7dEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["__SPxxQ7cEe-M7Mlv4-jcCw"] = ["Risk List","ProjectManagement/workproducts/risk_list_9879812E.html"];
contentPage.processPage.elementUrls["_HikeoA7cEe-M7Mlv4-jcCw"] = ["Develop_Business_Case","ProjectManagement/tasks/develop_business_case_669042E.html"];
contentPage.processPage.elementUrls["__SPxww7cEe-M7Mlv4-jcCw"] = ["Vision","ProjectManagement/workproducts/vision_7A95AF30.html"];
contentPage.processPage.elementUrls["_rIq-9Q7dEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_vMIp1w7cEe-M7Mlv4-jcCw"] = ["Vision","ProjectManagement/workproducts/vision_7A95AF30.html"];
contentPage.processPage.elementUrls["_WyiMQA7dEe-M7Mlv4-jcCw"] = ["Define_Project_Organization_and_Staffing","ProjectManagement/tasks/define_project_organization_and_staffing_4BDBFE36.html"];
contentPage.processPage.elementUrls["_vMIp0w7cEe-M7Mlv4-jcCw"] = ["Risk List","ProjectManagement/workproducts/risk_list_9879812E.html"];
contentPage.processPage.elementUrls["_ESkGcw7cEe-M7Mlv4-jcCw"] = ["Vision","ProjectManagement/workproducts/vision_7A95AF30.html"];
contentPage.processPage.elementUrls["_suma8Q7dEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["_4dgSEA7dEe-M7Mlv4-jcCw"] = ["Project_Acceptance_Review","ProjectManagement/tasks/project_acceptance_review_C4FA5486.html"];
contentPage.processPage.elementUrls["_4dgSGQ7dEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_szPf0Q7cEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_IErGIw7cEe-M7Mlv4-jcCw"] = ["Iteration Plan","ProjectManagement/workproducts/iteration_plan_6CFB48C4.html"];
contentPage.processPage.elementUrls["_O6lYlQ7dEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["_IErGIA7cEe-M7Mlv4-jcCw"] = ["Initiate Project","ProjectManagement/tasks/initiate_project_77C62FB5.html"];
contentPage.processPage.elementUrls["_RC6XAA7dEe-M7Mlv4-jcCw"] = ["Develop_Risk_Management_Plan","ProjectManagement/tasks/develop_risk_management_plan_38E532AA.html"];
contentPage.processPage.elementUrls["_MHESoQ7eEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_dYNqUQ7eEe-M7Mlv4-jcCw"] = ["Problem_Resolution_Plan","ProjectManagement/workproducts/problem_resolution_plan_9E3A5DFC.html"];
contentPage.processPage.elementUrls["_a-zi9w7eEe-M7Mlv4-jcCw"] = ["Issues_List","ProjectManagement/workproducts/issues_list_7FFD2B48.html"];
contentPage.processPage.elementUrls["_TbyS4Q7dEe-M7Mlv4-jcCw"] = ["Problem_Resolution_Plan","ProjectManagement/workproducts/problem_resolution_plan_9E3A5DFC.html"];
contentPage.processPage.elementUrls["_OCVsgQ7eEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_RC6XAQ7dEe-M7Mlv4-jcCw"] = ["Risk_Management_Plan","ProjectManagement/workproducts/risk_management_plan_EF36C2DA.html"];
contentPage.processPage.elementUrls["_AsjMkA7dEe-M7Mlv4-jcCw"] = ["Develop_Business_Case","ProjectManagement/tasks/develop_business_case_669042E.html"];
contentPage.processPage.elementUrls["_ESkGdQ7cEe-M7Mlv4-jcCw"] = ["Risk List","ProjectManagement/workproducts/risk_list_9879812E.html"];
contentPage.processPage.elementUrls["_szPf1Q7cEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_suma_w7dEe-M7Mlv4-jcCw"] = ["Development_Organization_Assesment","ProjectManagement/workproducts/development_organization_assesment_F8B466FC.html"];
contentPage.processPage.elementUrls["_ESkGcQ7cEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_Xf77oQ8bEe-Sh6UbRcOx-w"] = ["Plan_for_next_iteration","ProjectManagement/deliveryprocesses/Plan_for_next_iteration_AC2473BE.html"];
contentPage.processPage.elementUrls["_yoZf4Q7dEe-M7Mlv4-jcCw"] = ["Close-out_Project","ProjectManagement/capabilitypatterns/Close-out_Project_BA84AB71.html"];
contentPage.processPage.elementUrls["_MHESpQ7eEe-M7Mlv4-jcCw"] = ["Iteration_Assessment","ProjectManagement/workproducts/iteration_assessment_6D021373.html"];
contentPage.processPage.elementUrls["_a-zi-Q7eEe-M7Mlv4-jcCw"] = ["Risk List","ProjectManagement/workproducts/risk_list_9879812E.html"];
contentPage.processPage.elementUrls["_rIq-8Q7dEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_suma_Q7dEe-M7Mlv4-jcCw"] = ["Development_Case","ProjectManagement/workproducts/development_case_DF385ECD.html"];
contentPage.processPage.elementUrls["_bIKIsA7dEe-M7Mlv4-jcCw"] = ["Compile_Software_Development_Plan","ProjectManagement/tasks/compile_software_development_plan_CDD6BA3C.html"];
contentPage.processPage.elementUrls["_xrRlwQ7cEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["_suma9w7dEe-M7Mlv4-jcCw"] = ["Issues_List","ProjectManagement/workproducts/issues_list_7FFD2B48.html"];
contentPage.processPage.elementUrls["_aH-BkA7eEe-M7Mlv4-jcCw"] = ["PRA_Project_Review","ProjectManagement/tasks/pra_project_review_780C0427.html"];
contentPage.processPage.elementUrls["_xrRlwA7cEe-M7Mlv4-jcCw"] = ["Develop_Business_Case","ProjectManagement/tasks/develop_business_case_669042E.html"];
contentPage.processPage.elementUrls["_JSw0cQ7dEe-M7Mlv4-jcCw"] = ["Develop_Software_Development_Plan","ProjectManagement/capabilitypatterns/Develop_Software_Development_Plan_9969BBE2.html"];
contentPage.processPage.elementUrls["_O6lYkQ7dEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_MHESow7eEe-M7Mlv4-jcCw"] = ["Business Case","ProjectManagement/workproducts/business_case_5B23D182.html"];
contentPage.processPage.elementUrls["_R9g-EA7dEe-M7Mlv4-jcCw"] = ["Develop_Product_Acceptance_Plan","ProjectManagement/tasks/develop_product_acceptance_plan_DA94ED5C.html"];
contentPage.processPage.elementUrls["_aH-BkQ7eEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_suma9Q7dEe-M7Mlv4-jcCw"] = ["Measurement_Plan","ProjectManagement/workproducts/measurement_plan_DBFCF019.html"];
contentPage.processPage.elementUrls["__SPxwQ7cEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_WHStsQ8bEe-Sh6UbRcOx-w"] = ["Develop_Software_Development_Plan","ProjectManagement/deliveryprocesses/Develop_Software_Development_Plan_154639DE.html"];
contentPage.processPage.elementUrls["_4dgSEQ7dEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_IErGIQ7cEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_aH-BlQ7eEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_MHESoA7eEe-M7Mlv4-jcCw"] = ["Lifecycle_Milestone_Review","ProjectManagement/tasks/lifecycle_milestone_review_9AFFE01F.html"];
contentPage.processPage.elementUrls["_KO2MwQ7eEe-M7Mlv4-jcCw"] = ["Close-out_Phase","ProjectManagement/capabilitypatterns/Close-out_Phase_807B006C.html"];
contentPage.processPage.elementUrls["_MHESqQ7eEe-M7Mlv4-jcCw"] = ["Status_Assessment","ProjectManagement/workproducts/status_assessment_803C2A35.html"];
contentPage.processPage.elementUrls["_OCVsgw7eEe-M7Mlv4-jcCw"] = ["Issues_List","ProjectManagement/workproducts/issues_list_7FFD2B48.html"];
contentPage.processPage.elementUrls["_OCVsgA7eEe-M7Mlv4-jcCw"] = ["Prepare_for_Phase_Close_Out","ProjectManagement/tasks/preparre_for_phase_close_out_DDF1BA5E.html"];
contentPage.processPage.elementUrls["_WyiMQQ7dEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_O6lYkA7dEe-M7Mlv4-jcCw"] = ["Develop_Measurement_Plan","ProjectManagement/tasks/develop_measurement_plan_782C1ED8.html"];
contentPage.processPage.elementUrls["_UnxbsQ8bEe-Sh6UbRcOx-w"] = ["Evaluate_Project_Scope_and_Risk","ProjectManagement/deliveryprocesses/Evaluate_Project_Scope_and_Risk_EB5851EF.html"];
contentPage.processPage.elementUrls["_ccLVUw7dEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_vMIp0Q7cEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_G3m2EA7cEe-M7Mlv4-jcCw"] = ["Identify and assess Risks","ProjectManagement/tasks/identify_and_assess_risks_2485C8B9.html"];
contentPage.processPage.elementUrls["_5YLKkw7dEe-M7Mlv4-jcCw"] = ["Issues_List","ProjectManagement/workproducts/issues_list_7FFD2B48.html"];
contentPage.processPage.elementUrls["_b_QTUA7eEe-M7Mlv4-jcCw"] = ["Schedule_and_Assign_Work","ProjectManagement/tasks/schedule_and_assign_work_CB8520BD.html"];
contentPage.processPage.elementUrls["_O6lYmQ7dEe-M7Mlv4-jcCw"] = ["Measurement_Plan","ProjectManagement/workproducts/measurement_plan_DBFCF019.html"];
contentPage.processPage.elementUrls["_vMIp2Q7cEe-M7Mlv4-jcCw"] = ["Software_Arquitecture_Document","ProjectManagement/workproducts/software_arquitecture_document_B5A847C7.html"];
contentPage.processPage.elementUrls["_G3m2EQ7cEe-M7Mlv4-jcCw"] = ["Project Manager","ProjectManagement/roles/project_manager_D9AD5B94.html"];
contentPage.processPage.elementUrls["_7pydUQ7cEe-M7Mlv4-jcCw"] = ["Evaluate_Project_Scope_and_Risk","ProjectManagement/capabilitypatterns/Evaluate_Project_Scope_and_Risk_86DA71B1.html"];
contentPage.processPage.elementUrls["_b_QTUQ7eEe-M7Mlv4-jcCw"] = ["Work_Order","ProjectManagement/workproducts/work_order_CBF0790A.html"];
contentPage.processPage.elementUrls["_Zqc0kA7dEe-M7Mlv4-jcCw"] = ["Plan_Phases_and_Iterations","ProjectManagement/tasks/plan_phases_and_iterations_B0B05650.html"];
contentPage.processPage.elementUrls["_ccLVUQ7dEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_rIq-8w7dEe-M7Mlv4-jcCw"] = ["Iteration Plan","ProjectManagement/workproducts/iteration_plan_6CFB48C4.html"];
contentPage.processPage.elementUrls["_MHESqw7eEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_sGUS8A7dEe-M7Mlv4-jcCw"] = ["Initiate_Iteration","ProjectManagement/tasks/initiate_iteration_136847B6.html"];
contentPage.processPage.elementUrls["_hv-BAQ8bEe-Sh6UbRcOx-w"] = ["Develop_Software_Development_Plan","ProjectManagement/deliveryprocesses/Develop_Software_Development_Plan_55D8A7C1.html"];
contentPage.processPage.elementUrls["_szPf0w7cEe-M7Mlv4-jcCw"] = ["Iteration Plan","ProjectManagement/workproducts/iteration_plan_6CFB48C4.html"];
contentPage.processPage.elementUrls["_TbyS4A7dEe-M7Mlv4-jcCw"] = ["Develop_Problem_Resolution_Plan","ProjectManagement/tasks/develop_problem_resolution_plan_C337928B.html"];
contentPage.processPage.elementUrls["_dYNqUA7eEe-M7Mlv4-jcCw"] = ["Handle_Exceptions_and_Problems","ProjectManagement/tasks/handle_exceptions_and_problems_24B53152.html"];
contentPage.processPage.elementUrls["_vMIp1Q7cEe-M7Mlv4-jcCw"] = ["Software Development Plan","ProjectManagement/workproducts/software_development_plan_B82C47D0.html"];
contentPage.processPage.elementUrls["_qg83oA7dEe-M7Mlv4-jcCw"] = ["Iteration_Acceptance_Review","ProjectManagement/tasks/iteration_acceptance_review_7DC6671C.html"];
contentPage.processPage.elementUrls["_csP8MA7eEe-M7Mlv4-jcCw"] = ["Report_Status","ProjectManagement/tasks/report_status_2BBD8BE3.html"];
contentPage.processPage.elementUrls["_p3oN0Q7dEe-M7Mlv4-jcCw"] = ["Project Reviewer","ProjectManagement/roles/project_reviewer_EC027624.html"];
contentPage.processPage.elementUrls["_YlqNkQ8bEe-Sh6UbRcOx-w"] = ["Manage_Iteration","ProjectManagement/deliveryprocesses/Manage_Iteration_60F1C0C4.html"];
contentPage.processPage.elementUrls["_W8lDoQ7eEe-M7Mlv4-jcCw"] = ["Monitor_and_Control_Project","ProjectManagement/capabilitypatterns/Monitor_and_Control_Project_C81FC20E.html"];
contentPage.processPage.elementUrls["_U2IxAQ7dEe-M7Mlv4-jcCw"] = ["Quality_Assurance_Plan","ProjectManagement/workproducts/quality_assurance_plan_98D625C7.html"];
contentPage.processPage.elementUrls["_3L_40Q7bEe-M7Mlv4-jcCw"] = ["Conceive_New_Project","ProjectManagement/capabilitypatterns/Conceive_New_Project_CDEDCE7F.html"];
contentPage.processPage.elementUrls["_ccLVUA7dEe-M7Mlv4-jcCw"] = ["Project_Planning_Review","ProjectManagement/tasks/project_planning_review_C050334.html"];
contentPage.processPage.elementUrls["_7oodkQ8aEe-Sh6UbRcOx-w"] = ["Proceso","ProjectManagement/deliveryprocesses/Proceso_2C7F27C0.html"];
contentPage.processPage.elementUrls["_szPf0A7cEe-M7Mlv4-jcCw"] = ["Iteration_Plan_Review","ProjectManagement/tasks/iteration_plan_review_EF061A03.html"];
contentPage.processPage.elementUrls["_vMIp2w7cEe-M7Mlv4-jcCw"] = ["Requirements_Attributes","ProjectManagement/workproducts/requirements_attributes_7931538B.html"];
contentPage.processPage.elementUrls["_p3xXwg7dEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_YnjNIA7dEe-M7Mlv4-jcCw"] = ["Define_Monitoring_and_Control_Processes","ProjectManagement/tasks/define_monitoring_and_control_processes_702E759D.html"];
contentPage.processPage.elementUrls["_mlK-kQ7dEe-M7Mlv4-jcCw"] = ["Manage_Iteration","ProjectManagement/capabilitypatterns/Manage_Iteration_24614C99.html"];
contentPage.processPage.elementUrls["_suma8A7dEe-M7Mlv4-jcCw"] = ["Assess_Iteration","ProjectManagement/tasks/assess_iteration_9031BE16.html"];
contentPage.processPage.elementUrls["_zRMrsQuwEe-G3LyoK6aokA"] = ["Plan_for_next_iteration","ProjectManagement/capabilitypatterns/Plan_for_next_iteration_7A1635D4.html"];
contentPage.processPage.elementUrls["_vMIp0A7cEe-M7Mlv4-jcCw"] = ["Develop_Iteration_Plan","ProjectManagement/tasks/develop_iteration_plan_E79CD6B9.html"];
contentPage.processPage.elementUrls["_dSNcQQ8bEe-Sh6UbRcOx-w"] = ["Close-out_Project","ProjectManagement/deliveryprocesses/Close-out_Project_2AC98AB2.html"];
contentPage.processPage.elementUrls["_ESkGeQ7cEe-M7Mlv4-jcCw"] = ["Review Record","ProjectManagement/workproducts/review_record_CF0FA2D5.html"];
contentPage.processPage.elementUrls["_aH-Bkw7eEe-M7Mlv4-jcCw"] = ["Status_Assessment","ProjectManagement/workproducts/status_assessment_803C2A35.html"];
